{
  "openapi": "3.0.3",
  "info": {
    "title": "Dual Neural API — ChapterSets",
    "version": "0.1.0"
  },
  "paths": {
    "/chaptersets": {
      "get": {
        "summary": "Lista sets de capítulos",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ChapterSet"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Cria/atualiza set de capítulos",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ChapterSetCreate"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "ok": {
                      "type": "boolean"
                    },
                    "id": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Segment": {
        "type": "object",
        "properties": {
          "start": {
            "type": "number"
          },
          "duration": {
            "type": "number"
          },
          "label": {
            "type": "string"
          }
        },
        "required": [
          "start",
          "duration"
        ]
      },
      "ChapterSet": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "audioUrl": {
            "type": "string"
          },
          "duration": {
            "type": "number"
          },
          "segments": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Segment"
            }
          },
          "createdAt": {
            "type": "number"
          },
          "updatedAt": {
            "type": "number"
          },
          "meta": {
            "type": "object"
          }
        },
        "required": [
          "name",
          "segments"
        ]
      },
      "ChapterSetCreate": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "audioUrl": {
            "type": "string"
          },
          "duration": {
            "type": "number"
          },
          "segments": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Segment"
            }
          },
          "meta": {
            "type": "object"
          }
        },
        "required": [
          "name",
          "segments"
        ]
      }
    }
  }
}